shim-version: v0.2.5@sha256:ffdc7ca8e1a974c318533262c072b2c6c0871431b1e951fde7692388b5854cc3
cvm-version: 0.5.6
cpus: 16
memory: 32768

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
  publish-attestation: false
