shim-version: v0.3.11@sha256:c38fcc5db743dddf5dc986f67da8732b8a6c473e0e8e54d63826f46da278e290
cvm-version: 0.5.17
cpus: 128
memory: 1900544

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
