shim-version: v0.3.9@sha256:a45eb01f8e5fa3162b804821d53d8e8667a75940a9c1995f29265347efca8009
cvm-version: 0.5.16
cpus: 128
memory: 1048576

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
