shim-version: v0.3.13@sha256:e8d974949d08f86a36dd5b7dfa8681f222fcbdaf546ea952f97d2cf08305969d
cvm-version: 0.6.7
cpus: 128
memory: 1900544

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
