shim-version: v0.2.6@sha256:db5221f8e0c92562ddbe7d708a374ee0ca393bddc49e3ab2add5e23d8052b843
cvm-version: 0.5.6
cpus: 16
memory: 32768

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
  publish-attestation: false
