shim-version: v0.3.14@sha256:154c3e15f4d4856fd4b72e83f84da751abd34c76732bb6548bc89d5fa56c24ac
cvm-version: 0.6.7
cpus: 128
memory: 1900544

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
