shim-version: v0.3.18@sha256:7d9f98be78c91ede89f43c948a12d084fae34312effe9395ca7ed572991cb561
cvm-version: 0.6.7
cpus: 128
memory: 1900544

shim:
  listen-port: 443
  upstream-port: 8080
  tls-mode: self-signed
